### ISSUE TITLE
Possibility to set customized "selectedCaption"

### ISSUE THREAD

**Issue by thomaspp** [bonprix/vaadin-combobox-multiselect#12]
Hello,

Great addon. Very useful! I have a question:
Is it possible to define a customized "selectedCaption". Currently the following is used per default:

                if (selectedCaption.size() > 0) {
	        		target.addAttribute("selectedCaption",
	        				"(" + selectedCaption.size() + ") " + String.join("; ", selectedCaption));
                }

Thanks in advance!

Best Regards!

**Comment by thorbenvh8** [comment]
Hi,
I would be open for a pull request?
Best regards,
Thorben

**Comment by thomaspp** [comment]
Hello,

I have no experience with github / pull requests. What is required to do?

Best Regards,
Thomas

**Comment by thorbenvh8** [comment]
Hi,
well then you gonna learn something new today :)
[https://www.thinkful.com/learn/github-pull-request-tutorial/#Keep-Tabs-on-the-Project](url)
I hope this helps you with it :) 
Best regards,
Thorben

**Comment by thorbenvh8** [comment]
do you need any further help?

**Comment by thorbenvh8** [comment]
added setSelectedCaptionGenerator(...);
published in version: 1.1.11

gonna close this ticket

**Comment by thomaspp** [comment]
Thanks for that. I was the last days off (holiday). :-)
