### ISSUE TITLE
Paging not enabled for BeanItemContainer

### ISSUE THREAD

**Issue by wuyongqiang** [bonprix/vaadin-combobox-multiselect#13]
This is due to returning null when container is an instance of BeanItemContainer in the  implementation of method (line 563) :
protected List<?> getOptionsWithFilter(boolean needNullSelectOption)

I don't know why it is necessary to return null for BeanItemContainer.

**Comment by thorbenvh8** [comment]
are you on the newest version? (0.0.9)
we had some issues in some of the earlier versions, right now we have even ComboBoxMultiselect using a BeanItemContainer (vaadin-combobox-multiselect-demo/.../DemoUI.class)
Otherwise can you give a code example with your bug?

**Comment by wuyongqiang** [comment]
Thanks for your reply.
I can still see the code on the master branch in ComboBoxMultiselect.java. in my code (too complex to share at the moment, but may create a simple example later) I remove the condition (container instanceof BeanItemContainer), it works fine.

  if (container instanceof BeanItemContainer
        		|| !(container instanceof Filterable)
        		|| !(container instanceof Indexed)
        		|| !(container instanceof Sortable)
                || getItemCaptionMode() != ITEM_CAPTION_MODE_PROPERTY) {
            return null;
        }

**Comment by thorbenvh8** [comment]
the code that is around this is this:
because a beanitemcontainer is not filterable/sortable like the indexcontrainer;

List<?> options = getOptionsWithFilter(nullOptionVisible);
            if (null == options) {
                // not able to use container filters, perform explicit in-memory
                // filtering
                options = getSortedFilteredOptions();
                filteredSize = options.size();
                options = sanitetizeList(options, nullOptionVisible);
            }

is this working for you?
BeanItemContainer beanContainer = new BeanItemContainer(NamedObject.class);
		beanContainer.addBean(new NamedObject(1L, "Vaadin"));
		beanContainer.addBean(new NamedObject(2L, "Bonprix"));
		beanContainer.addBean(new NamedObject(3L, "ComboBox"));
		beanContainer.addBean(new NamedObject(4L, "Multiselect"));
		ComboBoxMultiselect beanComboBox = new ComboBoxMultiselect("beanItemContainer", beanContainer);
		beanComboBox.setShowSelectAllButton(new ShowButton() {
			
			@Override
			public boolean isShow(String filter, int page) {
				// TODO Auto-generated method stub
				return true;
			}
beanComboBox .setPageLength(3); // out of my head, not sure if this is the correct function syntax, but it will make it pageable for my 4 items (normal paging is 10 elements)
		});

**Comment by wuyongqiang** [comment]
This is my test code. I admit that this there is something you didn't excpect for the BeanitemContainer, which is a lazy one. The size of it is 12, but the next page is only loaded when it is needed.
private void addMultiSelect2(Layout layout) {
        // Initialize a list with items
        BeanItemContainer beanContainer = new BeanItemContainer(NamedObject.class){
            @Override
            public List<NamedObject> getItemIds(int startIndex, int numberOfIds) {
                List<NamedObject> results = new ArrayList<NamedObject>();
                // Set the last known start index after we have tried to retrieve the requested results because it is used in the above code.
                results.add(new NamedObject(9L, "Vaadin2", "Vaadin-desc2"));
                results.add(new NamedObject(10L, "Bonprix2", "Bonprix-desc2"));
                results.add(new NamedObject(11L, "ComboBox2", "ComboBox-desc2"));
                results.add(new NamedObject(12L, "Multiselect2", "Multiselect-desc2"));
                return results;
            }
            @Override
            public int size(){
                return 12;
            }
        };
        beanContainer.addBean(new NamedObject(1L, "Vaadin", "Vaadin-desc"));
        beanContainer.addBean(new NamedObject(2L, "Bonprix", "Bonprix-desc"));
        beanContainer.addBean(new NamedObject(3L, "ComboBox", "ComboBox-desc"));
        beanContainer.addBean(new NamedObject(4L, "Multiselect", "Multiselect-desc"));
        beanContainer.addBean(new NamedObject(5L, "Vaadin1", "Vaadin-desc1"));
        beanContainer.addBean(new NamedObject(6L, "Bonprix1", "Bonprix-desc1"));
        beanContainer.addBean(new NamedObject(7L, "ComboBox1", "ComboBox-desc1"));
        beanContainer.addBean(new NamedObject(8L, "Multiselect1", "Multiselect-desc1"));
        final ComboBoxMultiselect comboBoxMultiselect = new ComboBoxMultiselect("beanItemContainer", beanContainer);
        comboBoxMultiselect.setItemCaptionMode(ItemCaptionMode.PROPERTY);
        comboBoxMultiselect.setItemCaptionPropertyId("value");
        comboBoxMultiselect.setPageLength(8);
        comboBoxMultiselect.setInputPrompt("Type here");

        comboBoxMultiselect.setNewItemsAllowed(true);
        comboBoxMultiselect.setFilteringMode(FilteringMode.OFF);
        comboBoxMultiselect.setStyleName("multi-select");
        comboBoxMultiselect.setWidth(200, Unit.PIXELS);
        comboBoxMultiselect.setHeight(20, Unit.PIXELS);

        comboBoxMultiselect.addValueChangeListener(e -> multiSelectChanged(e, comboBoxMultiselect));

        layout.addComponent(comboBoxMultiselect);
    }

**Comment by thorbenvh8** [comment]
if i understand your code correctly, youre overriding the beanitemcontainer to retrieve the last called pageindex?
wouldnt it be better to develop a pagechangelistener for the beanitemcombobox instead of overriding functions?

**Comment by wuyongqiang** [comment]
Seems I cannot get page event because paging is not enabled yet.

**Comment by thorbenvh8** [comment]
there is no pagechangelistener yet in it, you could develop something like that for it. My question was if thats what you really need, because then you dont need to override functions inside the beanitemcontainer?

**Comment by wuyongqiang** [comment]
Yes, the lazy loading is something i really need. I fear that even pagechangelistener is added, it won't be triggered, because the paging is not enabled in the first place.

**Comment by wuyongqiang** [comment]
I'm wondering what damage would it have to remove the first condition (container instanceof BeanItemContainer) from the following statement. In my test, it looks OK.

if (container instanceof BeanItemContainer
|| !(container instanceof Filterable)
|| !(container instanceof Indexed)
|| !(container instanceof Sortable)
|| getItemCaptionMode() != ITEM_CAPTION_MODE_PROPERTY) {
return null;
}

**Comment by thorbenvh8** [comment]
when you do all this to have a lazyloading feature, why dont you use the lazyloadingcontainer?
https://vaadin.com/directory#!addon/lazy-query-container

**Comment by wuyongqiang** [comment]
Many thanks. This is a very good recommendation. I'll look at it.

**Comment by thorbenvh8** [comment]
please give me an update or what we have to do to make the comboboxmultiselect be able to use the lazyloadingcontainer :)

**Comment by wuyongqiang** [comment]
Sure, I'll do.

**Comment by thorbenvh8** [comment]
is it working for you?

**Comment by wuyongqiang** [comment]
Sorry, not done yet, and will let you once get on it. Cheers.

**Comment by wuyongqiang** [comment]
I have done a simple test with the code below, and it is confirmed that the lazycontainer is working for the paging issue. Thanks to Thorben.

private void addSelectUsingLazyQueryContainer(Layout layout) {

        QueryContainer cityContainer = null;
        QueryFactory queryFactory = new QueryFactory() {

            @Override
            public Query constructQuery(QueryDefinition queryDefinition) {
                // TODO Auto-generated method stub
                return new Query() {

                    @Override
                    public int size() {
                        return 100;
                    }

                    @Override
                    public void saveItems(List<Item> addedItems, List<Item> modifiedItems, List<Item> removedItems) {
                        // do nothing

                    }

                    @Override
                    public List<Item> loadItems(int startIndex, int count) {
                        List<Item> result = new ArrayList<Item>();
                        if (count > 10) count = 10;
                        for (int i = 0; i < count; i++) {
                            Item item = constructItem();
                            item.getItemProperty("name").setValue("name " + (i + startIndex));
                            item.getItemProperty("resource").setValue("resource " + (i + startIndex));
                            item.getItemProperty("unknown").setValue("unknown " + (i + startIndex));
                            result.add(item);
                        }
                        return result;
                    }

                    @Override
                    public boolean deleteAllItems() {
                        // doing nothing
                        return false;
                    }

                    @Override
                    public Item constructItem() {

                        Item item = new PropertysetItem();
                        item.addItemProperty("selected", new ObjectProperty<Boolean>(false));
                        item.addItemProperty("name", new ObjectProperty<String>(""));
                        item.addItemProperty("resource", new ObjectProperty<String>(""));
                        item.addItemProperty("unknown", new ObjectProperty<String>(""));

                        return item;
                    }
                };
            }
        };
        cityContainer = new QueryContainer(queryFactory, null, 10, false);
        cityContainer.getQueryView().getQueryDefinition().setMaxQuerySize(1000);

        final ComboBoxMultiselect select = new ComboBoxMultiselect("IndexedContainer", cityContainer);
        select.setWidth(200, Unit.PIXELS);
        select.setItemCaptionPropertyId("name");
        select.setItemCaptionMode(ItemCaptionMode.PROPERTY);
        select.setIcon(FontAwesome.BOLD);    
        layout.addComponent(select);
    }

**Comment by thorbenvh8** [comment]
ok nice :)
closing the issue :)
