### ISSUE TITLE
select all

### ISSUE THREAD

**Issue by zsu153** [bonprix/vaadin-combobox-multiselect#16]
Hi,

I'm happily using the new features of combobox-multiselect, specially the "select all" button and function. 

I have three of them on my UI, with many items (>1000), I need every item selected by default, but it took relatively a long time. Timetests showed, that 
`ComboBoxMultiselect#selectAll()`
caused the slowness. I've noticed, that this method selects the items one-by-one. I've changed it to 
`cbms.setValue(cbms.getItemIds());`
it makes the selection all at once, and it solved my problem.

Just a suggestion, take it if you like.

Zsu

**Comment by thorbenvh8** [comment]
Thanks, what line are you referring to? Can you make it as a pull request? :)
Very appreciate the input :)

**Comment by zsu153** [comment]
I've meant this part of ComboBoxMultiselect:
```
    public void select(Collection<Object> itemIds) {
    	for (Object itemId : itemIds) {
    		super.select(itemId);
		}
    }
	
	@SuppressWarnings("unchecked")
	public void selectAll() {
		select((Collection<Object>) getItemIds());
	}
```
Was I clear? I'm new in github, must look after, what is a "Pull request" :)

**Comment by thorbenvh8** [comment]
```java
@SuppressWarnings("unchecked")
public void selectAll() {
	setValue(new HashSet<Object>((Collection<?>) getItemIds()));
}
```

I tried out this immutable version of your change to make it not more secure :)
what do you think?

**Comment by thorbenvh8** [comment]
added setSelectedCaptionGenerator(...);
published in version: 1.1.11

gonna close this ticket

**Comment by thorbenvh8** [comment]
added this implementation in version 1.1.11 :)

**Comment by zsu153** [comment]
I find your change ok. Thanks for your quick response, I will try out the new version soon.
