### ISSUE TITLE
Problem with caption

### ISSUE THREAD

**Issue by MajewskiKrzysztof** [bonprix/vaadin-combobox-multiselect#17]
Hello,
I am using your comopnent as a filter in a grid column

```
final ComboBoxMultiselect selectionBox = new ComboBoxMultiselect(new ComboBoxMultiselectCaptions("nothing selected", "multiple selection"));
selectionBox.setClearButtonCaption("clear");
selectionBox.addItems(currencyCodes);
selectionBox.select(currencyCodes);
selectionBox.setWidth(100, Sizeable.Unit.PIXELS);

Grid.HeaderCell statusHeaderCell = mainGrid.getHeaderRow(1).getCell(COLUMN_3);
statusHeaderCell.setComponent(selectionBox);
```
I've added a blur listener to filter my grid:

```
selectionBox.addBlurListener(new FieldEvents.BlurListener() {
    @Override
    public void blur(FieldEvents.BlurEvent event) {
          filterMyGrid(myGrid, (Set) selectionBox.getValue());
});

```
The problem is when I select multiple items caption doesn't change to "multiple selections". Instead it looks like that: "(count) item1, item2, item3, ..."
![combomultibadcaption](https://cloud.githubusercontent.com/assets/17272805/17643983/d1d82c1a-617a-11e6-904e-f4aa3918ea08.png)

I've managed to change it by adding setInputPrompt() in blur listener:

```
public void blur(FieldEvents.BlurEvent event) {
        if (((Set) selectionBox.getValue()).size() == 0)
            selectionBox.setInputPrompt("nothing selected");
        else if (((Set) selectionBox.getValue()).size() > 1)
            selectionBox.setInputPrompt("multiple selection");
        else
            selectionBox.setInputPrompt(selectionBox.getCaption());

       filterMyGrid(myGrid, (Set) selectionBox.getValue());
}
```

Although it doesn't work 100% right. After the component loses focus caption still displays as "(count) item1, item2, item3, ..." and changes to correct one after the grid is refreshed.

I've also noticed that when I put a breakpoint in my blurlistener and click somewhere else in my app the caption changes to "(count) item1, item2, item3, ...", so it it works like a focus listener. 

I've looked everywhere in your code and I don't think that your component makes that problem. Do you have any idea what is causing this?

**Comment by thorbenvh8** [comment]
1. well its because the javascript part will still trigger events even though your java code is in debug at a breakpoint.
2. there is another open issue for a selectionCaptionGenerator to make it more easy to change my default "(count) ..." implementation. Like I told in the other ticket I would be open for a pull request. :)

I will keep this ticket open for your response if you want to make a pull request for the generator :)

**Comment by MajewskiKrzysztof** [comment]
There is something that I do not understand. I've changed this:

```
if (selectedCaption.size() > 0) {
    target.addAttribute("selectedCaption",
         "(" + selectedCaption.size() + ") " + String.join("; ", selectedCaption));
}
```

into:

```
if (selectedCaption.size() > 0) {
    target.addAttribute("selectedCaption", "Is it working?");
```

But it is still displaying "(count) item1, ..."

**Comment by thorbenvh8** [comment]
did you build it with mvn clean install and refreshed your maven dependencies? :)

**Comment by MajewskiKrzysztof** [comment]
Yes, I did

**Comment by thorbenvh8** [comment]
<img width="709" alt="screenshot 2016-08-13 19 20 33" src="https://cloud.githubusercontent.com/assets/5954736/17644586/199741c0-618b-11e6-8aa8-e182d498bbc3.png">
did you do mvn clean install on the parent project? and did you try closing the widget project and forcing maven to update the dependencies?

**Comment by thorbenvh8** [comment]
added setSelectedCaptionGenerator(...);
published in version: 1.1.11

gonna close this ticket

**Comment by thomaspp** [comment]
Hello!

I have the same issue and no idea why it shows always "(count), item 1, ...". Only on a refresh the implemented caption is shown. The correct selectionCaptionGenerator is called, but the wrong value is shown.

Regards,
Thomas

**Comment by MajewskiKrzysztof** [comment]
version: 1.1.11 doesn't solved this problem.

This is my `selectedCaptionGenerator`

```
    public ComboBoxMultiselect(final MyCaptionsContainercaptions) {
        setSelectedCaptionGenerator(new SelectedCaptionGenerator() {
            @Override
            public String getSelectedCaption(List<String> selectedCaptions) {
                if(selectedCaptions.size() == 0)
                    return captions.getNoSelection();
                else if(selectedCaptions.size() == 1)
                    return selectedCaptions.get(0);
                else
                    return captions.getMultipleSelection();
            }
        });
        initDefaults();
    }
```

And this is how it looks after selection change:

![caption](https://cloud.githubusercontent.com/assets/17272805/17698398/4e13da3a-63bb-11e6-9d7e-c902c2173d2f.jpg)

I've cleaned and rebuilded my project. I have no idea what is causing this.

**Comment by thorbenvh8** [comment]
yes i see the problem now. it gets generated on the client side... 
https://github.com/bonprix/vaadin-combobox-multiselect/blob/master/vaadin-combobox-multiselect/src/main/java/org/vaadin/addons/comboboxmultiselect/client/VComboBoxMultiselect.java#L2321
I have no idea how to solve this. I cant get an interface through to the client side.
Anybody have any idea?

**Comment by thorbenvh8** [comment]
the only thing i could think of setting two values
by default its my "(x) ..." but if you set this values it will be overwritten on client side as well like this
String singleselectcaption = "whatever";
String multiselectioncaption = "whatever";
but no calculation in the caption is possible then.

what do you think?

**Comment by thomaspp** [comment]
If I understand you correct, you want to have a fix value, if the user select one/multiple items? This value can be configured? I think this is okay :-)

**Comment by thorbenvh8** [comment]
added setSelectionStaticCaption(String singleSelectionCaption, String multiSelectionCaption) for using your own static caption when items are selected;

Version 1.1.12

**Comment by thomaspp** [comment]
Hello,

Maybe I do something wrong. But it seems that it is still the same issue? The static caption is only shown, if the page will be refreshed. Further to this a lot of console outputs are available.

Best Regards,
Thomas

**Comment by thorbenvh8** [comment]
sorry about the logging forgot the deactivate the variable to false again ;)

but the other stuff should work, look how it looks for me, can you please recheck? Maybe recompile your widgetset?
[staticcaption.zip](https://github.com/bonprix/vaadin-combobox-multiselect/files/428247/staticcaption.zip)

**Comment by thomaspp** [comment]
Oh yes, perfect. It works now!! Thanks a lot! :-)

**Comment by thomaspp** [comment]
Do you create a new release for it? :)

**Comment by thorbenvh8** [comment]
no i didnt change anything ;) i waited for you to test the latest to make it into a new one without the login if it works already :)

**Comment by thorbenvh8** [comment]
new version 1.1.13 :)

**Comment by thomaspp** [comment]
Thanks a lot :-)

**Comment by thomaspp** [comment]
It seems that the console outputs are not gone after the release? :-D

**Comment by thorbenvh8** [comment]
sorry so much logging ;) 1.1.14 ;)

**Comment by MajewskiKrzysztof** [comment]
I have a problem with clear button. When i select few items and click "clear" it doesn't do anything. Only after I click somewhere else in my app the list hides and instantly shows a new empty one. Do you have this problem too?

**Comment by thorbenvh8** [comment]
i tried it and i dont have it at all
