### ISSUE TITLE
filtering values

### ISSUE THREAD

**Issue by evanzel** [bonprix/vaadin-combobox-multiselect#2]
Seems that while filtering works when there is some value for items to be filtered with; it breaks when you put something and then delete it.
The full list of items will not be presented again.

**Comment by thorbenvh8** [comment]
Ok im redoing the whole project right now, to not use server side components instead of making an update on the VFilterSelect from Vaadin.
Hopefully gonna be updating that after the weekend.
Thanks for your help, gonna try to fix it in the new one :)

**Comment by thorbenvh8** [comment]
I updated the ComboBoxMultiselect to a client side widget now :)
Please check, im gonna close this now, hoping for your feedback :)
