### ISSUE TITLE
Using setValue() progamatically is not refreshing the UI

### ISSUE THREAD

**Issue by brunojcm** [bonprix/vaadin-combobox-multiselect#21]
I did the following test, using version 1.1.11 and Vaadin 7.6.8:

		BeanItemContainer<Office> testContainer = new BeanItemContainer<>(Office.class);
		Office o1 = new Office();
		o1.setName("Office 1");
		testContainer.addBean(o1);
		Office o2 = new Office();
		o2.setName("Office 2");
		testContainer.addBean(o2);
		
		ComboBoxMultiselect c = new ComboBoxMultiselect(null, testContainer);
		c.setWidth("300");
		addComponent(c);
		
		Button but = new Button("setValueToO1", e -> c.setValue(new HashSet<>(Arrays.asList( o1 ))));
		addComponent(but);

`Office` is just a simple bean with a property `name`, and `equals()` and `hashcode()` using this property.

The steps I did were:

1. Open ComboBoxMultiselect and select Office 2
2. Click anywhere outside
3. ComboBoxMultiselect shows "(1) Office 2" correclty
4. Click "setValueToO1" button
5. ComboBoxMultiselect keeps showing "(1) Office 2", and if I open it, "Office 2" is checked instead of "Office 1".

I debugged `com.vaadin.ui.AbstractField.setValue(T, boolean, boolean)` and it seems to set the internal value correctly, but it is not reflected on the UI, it behaves like "Office 2" is still checked.

Any ideas?

I'm trying to understand things on the server side, but when it flows beyond `markAsDirty()`, I get lost because I don't know how Vaadin works on this matter.

**Comment by thorbenvh8** [comment]
[combobox_button_select.zip](https://github.com/bonprix/vaadin-combobox-multiselect/files/417138/combobox_button_select.zip)
it works for me, look at the video please.
My code:
```java
BeanItemContainer<NamedObject> beanContainer = new BeanItemContainer<NamedObject>(NamedObject.class);
		final NamedObject vaadin = new NamedObject(1L, "Vaadin");
		beanContainer.addBean(vaadin);
		beanContainer.addBean(new NamedObject(2L, "Bonprix"));
		beanContainer.addBean(new NamedObject(3L, "ComboBox"));
		beanContainer.addBean(new NamedObject(4L, "Multiselect"));
		final ComboBoxMultiselect beanComboBox = new ComboBoxMultiselect("beanItemContainer", beanContainer);
		beanComboBox.setPageLength(3);
		beanComboBox.setShowSelectAllButton(new ShowButton() {
			
			@Override
			public boolean isShow(String filter, int page) {
				// TODO Auto-generated method stub
				return true;
			}
		});
		main.addComponent(beanComboBox);
		
		Button but = new Button("setValueToO1");
		but.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				beanComboBox.setValue(new HashSet<NamedObject>(Arrays.asList(vaadin)));
			}
			
		});
	    main.addComponent(but);
```

I dont know what your problem is :(

**Comment by brunojcm** [comment]
Figured it out!!
I was using ComboBoxMultiselect inside a library, whose dependency I upgraded to 1.1.11, but the web project was still compiling the widgetset with the old 1.1.0 ;)
So I think I was using 1.1.11 server code with 1.1.0 widgetset... Everything could happen in this case! :)

**Comment by thorbenvh8** [comment]
ok good to know, but I have no idea how you would even able to do that. :) Glad it works now :)
