### ISSUE TITLE
Reindeer Theme error

### ISSUE THREAD

**Issue by ofbizbrazil** [bonprix/vaadin-combobox-multiselect#26]
If we try to add ComboBoxMultiselect using Reindeer theme, the component freezes and is not possible click in the checkbox, only via caption text works to select the checkbox.

**See code:**

```
        BeanItemContainer<NamedObject> beanContainer = new BeanItemContainer<NamedObject>(NamedObject.class);
        beanContainer.addBean(new NamedObject(2L, "Bonprix"));
        beanContainer.addBean(new NamedObject(3L, "ComboBox"));
        beanContainer.addBean(new NamedObject(4L, "Multiselect"));

        final ComboBoxMultiselect beanComboBox = new ComboBoxMultiselect("beanItemContainer", beanContainer);

        final VerticalLayout vertical = new VerticalLayout();
        vertical.addComponent(beanComboBox);
```

**Comment by thorbenvh8** [comment]
sorry for the late response,
could you fix it for yourself via a pullrequest?
The bug should be somewhere in the VComboBoxMultiselect class where I check for the clicking on the checkbox.

**Comment by thorbenvh8** [comment]
closed because of inactivity
