### ISSUE TITLE
Exclude rebel.xml from the jar

### ISSUE THREAD

**Issue by sularak** [bonprix/vaadin-combobox-multiselect#27]
It would be great if the rebel.xml could be excluded from the jar. 

When I use this Vaadin Add-on in my project, I get repeatedly an error notification: 
Invalid 'dir' defined in class path of rebel.xml (jar:file:.../WEB-INF/lib/vaadin-combobox-multiselect-1.1.14.jar!/rebel.xml): Directory '/Users/thorbenvh8/Documents/workspace/vaadin-combobox-multiselect/vaadin-combobox-multiselect/target/classes' does not exist

**Comment by thorbenvh8** [comment]
done in 1.2.0
