### ISSUE TITLE
String.Join error

### ISSUE THREAD

**Issue by oxygenpt** [bonprix/vaadin-combobox-multiselect#28]
It would be great if the String.join use could be replaced in a way that work while executing Java 7. 
In many cases (as my own) can be extremely difficult to replace java to version 8.

See error:

`java.lang.NoSuchMethodError: java.lang.String.join(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String;
	at org.vaadin.addons.comboboxmultiselect.ComboBoxMultiselect.paintContent(ComboBoxMultiselect.java:496) [vaadin-combobox-multiselect-1.1.14.jar:1.1.14]`

**Comment by thorbenvh8** [comment]
im open for a pullrequest

**Comment by thorbenvh8** [comment]
i will try to release a version next week :) thanks :)

**Comment by oxygenpt** [comment]
Hi there,
Will you be able to release any time soon? 
Thanks in advance!

**Comment by thorbenvh8** [comment]
sorry for the long time... fixed in 1.2.0

**Comment by oxygenpt** [comment]
I'm sorry for the late answer. Thank you very much.
