### ISSUE TITLE
Exclude cache from widgetset compilation in Jar

### ISSUE THREAD

**Issue by sebastianfilke** [bonprix/vaadin-combobox-multiselect#32]
I get an exception with jrebel with this addon:

[2017-02-24 10:33:56] Invalid rebel.xml: Invalid 'dir' defined in class path of rebel.xml  Directory 'C:/bpPrograms/Java/workspace/workspace_mars2/vaadin-combobox-multiselect-root/vaadin-combobox-multiselect/target/classes' does not exist

Searching in this repository let me find this file:

https://raw.githubusercontent.com/bonprix/vaadin-combobox-multiselect/e82e8d7618243587ea090824cbaf8b54e2f94317/vaadin-combobox-multiselect-demo/src/main/webapp/VAADIN/themes/demo/styles.scss.cache

In the first line there ist the string from above. Try to exclude this cache file in compilation.
This is from the single-application-archetype from vaadin:

`<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					
					<packagingExcludes>WEB-INF/classes/VAADIN/widgetsets/WEB-INF/**</packagingExcludes>
				</configuration>
			</plugin>`

Mybe this helps

**Comment by sebastianfilke** [comment]
The configuration seems okay. The file file above styles.scss.cache should be deleted and added to .gitignore

**Comment by thorbenvh8** [comment]
@sebastianfilke did you fix this as well already?

**Comment by sebastianfilke** [comment]
This bug seems fixed but the version which is uploaded to vaadin repository has a rebel.xml included which results in this exception. Do you build the application on your machine?

This is the exception: `[2017-04-18 08:44:18] Invalid rebel.xml: Invalid 'dir' defined in class path of rebel.xml (jar:file:/C:/Oracle/glassfish4.1.1/glassfish/domains/qkiss/eclipseApps/alegria-qkiss-webportal-ear/alegria-qkiss-webportal-ui-1.3.0-SNAPSHOT_war/WEB-INF/lib/vaadin-combobox-multiselect-2.0.1.jar!/rebel.xml): Directory 'C:/bpPrograms/Java/workspace/workspace_mars2/vaadin-combobox-multiselect-root/vaadin-combobox-multiselect/target/classes' does not exist`

![image](https://cloud.githubusercontent.com/assets/10894484/25117796/dccd99be-2413-11e7-8f9d-404623c915ef.png)

This is the content of the file which produces the error:
```
<?xml version="1.0" encoding="UTF-8"?>
<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.zeroturnaround.com" xsi:schemaLocation="http://www.zeroturnaround.com http://www.zeroturnaround.com/alderaan/rebel-2_0.xsd">

	<classpath>
		<dir name="C:/bpPrograms/Java/workspace/workspace_mars2/vaadin-combobox-multiselect-root/vaadin-combobox-multiselect/target/classes">
		</dir>
	</classpath>

</application>
```
I will open a new bug.
