### ISSUE TITLE
Support Vaadin 8

### ISSUE THREAD

**Issue by sebastianfilke** [bonprix/vaadin-combobox-multiselect#34]

**Comment by aley2003** [comment]
Thanx for the Vaadin 8 support.
But if I try to integrate 'org.vaadin.addons:vaadin-combobox-multiselect:2.0.0' in my Vaadin 8.0.4 project I get:

> Error:Could not find org.vaadin.addons:vaadin-combobox-multiselect-root:2.0.0.

**Comment by sebastianfilke** [comment]
Thats true, i hadn't this problem because i migrated this addon and it seems that the dependency are in my local repository. One of my collegues had the same problem.

**Comment by sebastianfilke** [comment]
Okay, the problem is that now there is a parent in the addon pom.xml. The addon is looking for it but can't find it in the addon repository from vaadin.

Two ways to fix it:

- Either switch back to a maven structure without a parent
- Upload the parent project (maybe also the demo) in the vaadin addon repo. i don't know how addon uploads are done!

What do you mean @thorbenvh8? Should i switch back to the old project structure (only remove parent from addon and demo, so to make them standalone again.)

**Comment by thorbenvh8** [comment]
yes please

**Comment by sebastianfilke** [comment]
Okay, the problem is another one. Which version have you uploaded to vaadin?
5196b811407693a935b7cc0e77ca87a69cba5a5b?

In this last commit you only updated the parent pom.xml version to 2.0.1-SNAPSHOT but neither the version of the reference of the parent pom.xml from the "vaadin-combobox-multiselect" project nor the version of the parent from the "vaadin-combobox-multiselect-demo" project. so this two projects can't find the parent.

**Comment by sebastianfilke** [comment]
Okay, i will Change it maybe tomorrow or monday:-)

**Comment by sebastianfilke** [comment]
@thorbenvh8 I created a pull request #36 for the project structure. Please update the vaadin addon in the directory. We need this addon! Thank you very much.

**Comment by estronque** [comment]
Hi I would like to use this component, but it doesnt work: Failed to read artifact descriptor for org.vaadin.addons:vaadin-combobox-multiselect:jar:2.0.0: Failure to find org.vaadin.addons:vaadin-combobox-multiselect-root:pom:2.0.0. 
Someone has the same problem?

**Comment by sebastianfilke** [comment]
Look here #36. I created this pull request a couple of days ago. But don't get feedback yet. I hope this bugfix will be out very soon.

**Comment by thorbenvh8** [comment]
sorry for the late response.
@sebastianfilke fixed it in 2.0.1

**Comment by aley2003** [comment]
I have tried to use 2.0.1 with Vaadin 8.0.5 but I get:
Unable to find 'com/vaadin/v7/Vaadin7WidgetSet.gwt.xml' on your classpath
Why does vaadin-combobox-multiselect need the Vaadin 7 WidgetSet? 
We want to use Vaadin 8 not Vaadin 7. Does vaadin-combobox-multiselect support the compatibility classes only?

**Comment by brunojcm** [comment]
> Why does vaadin-combobox-multiselect need the Vaadin 7 WidgetSet?

The support for Vaadin 8 still uses the compatibility layer to Vaadin 7, AFAIK.
