### ISSUE TITLE
java.lang.NoClassDefFoundError exception on ComboboxMultiselect

### ISSUE THREAD

**Issue by KuralManivannan** [bonprix/vaadin-combobox-multiselect#4]
I'm getting java.lang.NoClassDefFoundError: org/vaadin/addons/comboboxmultiselect/ComboBoxMultiselect exception on using the ComboboxMultiselect addon. I have added the jar in class path as well as in my WEB-INF/lib folder.

**Comment by thorbenvh8** [comment]
I have no solution at all for this. Having the same issue sometimes too when eclipse is mixing up the dependencies. Maven -> update -> force update snapshot/release works for me.
