### ISSUE TITLE
Use Vaadin 8 features without compatibility packages

### ISSUE THREAD

**Issue by sebastianfilke** [bonprix/vaadin-combobox-multiselect#41]
Is there a plan to rewrite the addon to use Vaadin 8 components and field structures without containers like in Vaadin 7. So that the multiselect combobox can use generics?

**Comment by thorbenvh8** [comment]
currently this project was developed for vaadin7, since for my company we are not using vaadin8 we will not develop this for vaadin8 yet. If you want to make a pull request for this we would be very open for this.

**Comment by thorbenvh8** [comment]
we will work on this in the next couple weeks!

**Comment by kolle1986** [comment]
Please! :)

**Comment by thorbenvh8** [comment]
we have upgraded it to vaadin8 completely, but right now Addon upload doesnt work, so you have to build it localy and push it in your own artifactory manually for now.
