### ISSUE TITLE
Add option to open ja filter Dialog

### ISSUE THREAD

**Issue by jamariSetual** [bonprix/vaadin-combobox-multiselect#43]
Like 'clear' and 'select all' it would be nice to add an option to open a more detailed dialog (customer created). 

The filter is filtering people, the display value is 'name, prename'. Now, I want to filter all, with an age over 18 or who lived in a country I choose. But, i dont want to show these attributes in the orignial table.  What happens on 'selected on detail' should handled by a concred implementation.

**Comment by thorbenvh8** [comment]
we will look into it

**Comment by thorbenvh8** [comment]
any idea how to implement this? If I understand it correct you want a more specific way to filter?

**Comment by jamariSetual** [comment]
I added a button before the combobox:

[Button][Combobox]

e.g.
The combobox let you select a Person:

Meier, Susanne
Schmidt, Holger
Mustermann, Hans

If you click the Button, a addon will open:

Meier ... Susanne ... Frau ... 1976
Schmidt ... Holger .... Herr ... 1980
Mustermann ... Hans ... Herr ... 1960

Thats a grid, where you can selcet and filter as you like. I saw at a presenation of another software, that the combobox doesn't open a popup to disply only one property, they display a Grid to filter (like i had done it now in a Dialog).

At least, now i implement the Dialog with the Grid on my own. But it Could be a default way to use it, I already add a Container to the Combobox, i only need to say, which columns i want to show in the Grid.

Hope its more clear now.

**Comment by thorbenvh8** [comment]
ok this seems very specific to you :) since you have a solution i will close the ticket, but if you ever want to make a pull request, we would be open to it :)
