### ISSUE TITLE
NULL Option  (nullSelectionAllowed)

### ISSUE THREAD

**Issue by jamariSetual** [bonprix/vaadin-combobox-multiselect#44]
It seems you removed the NULL selection. 

Is it possible to get them back? NULL is in normal Grids a valid value. The Side-Effects missing it are hugh

**Comment by thorbenvh8** [comment]
hi,
i dont really understand the problem. A multiselect combobox by default is nullselectionallowed, you cant really change that currently.
Maybe try to have the value initialized with an empty list?

**Comment by thorbenvh8** [comment]
no response close
