### ISSUE TITLE
Doesn't work with Vaadin 8.1.0

### ISSUE THREAD

**Issue by ThomasEll** [bonprix/vaadin-combobox-multiselect#48]
When adding version 2.0.1 to my POM dependencies I get the following error

[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:8.1.0:compile (default) on project supplierPortal: GWT Module com.vaadin.v7.Vaadin7WidgetSet not found in project sources or resources. -> [Help 1]

I'm not sure if some compatibility features were removed when Vaadin moved to 8.1.0

**Comment by thorbenvh8** [comment]
hopefully we are migratin it to real vaadin8 in the next two weeks! :)

**Comment by tomekkup** [comment]
yeah. I'm waiting for next release too. Need to use this plugin with v8.1.0

**Comment by brunojcm** [comment]
I just did the #50 pull request to fix this.
This probably require a major release, since it is no longer compatible with standard Vaadin 7 libraries once we tie the implementation to Vaadin 8's Vaadin 7 compatibility package. Confusing, ah?

If you are in a hurry, I just published an artifact with this change in my company's repo. You can use it with the following configuration:

	<repositories>
		<repository>
			<id>visagio-public-releases</id>
			<url>https://artifacts.visagio.com/artifactory/public-releases</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>


Dependency:

		<dependency>
			<groupId>org.vaadin.addons</groupId>
			<artifactId>vaadin-combobox-multiselect</artifactId>
			<version>1.8-visagio-1</version>
		</dependency>

**Comment by thomaspp** [comment]
Hello! What do I have to add in my gradle file to get this library?

**Comment by brunojcm** [comment]
@thomaspp This seems more a gradle-realated question, but maybe [this question](https://stackoverflow.com/questions/20574111/add-maven-repository-to-build-gradle) can help you.

**Comment by Fantom0x00F** [comment]
If you don't want to wait for next release and don't want to use brunojcm repository, then just add this dependency
```
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-compatibility-client</artifactId>
        </dependency>
```

**Comment by brunojcm** [comment]
@Fantom0x00F, how does this fix the problem?

**Comment by Fantom0x00F** [comment]
@brunojcm I just followed the instructions from [documentation](https://vaadin.com/docs/v8/framework/getting-started/getting-started-libraries.html), that says that for easy migration from version 7 to version 8 you need to add a *vaadin-compatibility-** dependencies. And it works for me

**Comment by brunojcm** [comment]
@Fantom0x00F  Are you really using the latest version of Vaadin 8 and this add-on? I cannot see how it could work, as this add-on does not provide a compatibility package itself and still compiles against the classes in the packages they were on Vaddin 7 (and not in the compatibility `com.vaadin.v7.* ` packages). But well, if it works somehow, nice, then. :)

**Comment by Fantom0x00F** [comment]
@brunojcm Yes, i use the latest versions and vaadin-maven-plugin with configuration:
```
<plugin>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-maven-plugin</artifactId>
    <version>${vaadin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>update-widgetset</goal>
                <goal>compile</goal>
                <goal>update-theme</goal>
                <goal>compile-theme</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by thorbenvh8** [comment]
we have upgraded it to vaadin8 completely, but right now Addon upload doesnt work, so you have to build it localy and push it in your own artifactory manually for now.
