### ISSUE TITLE
rebel.xml still included in vaadin-combobox-multiselect-2.0.1

### ISSUE THREAD

**Issue by sebastianfilke** [bonprix/vaadin-combobox-multiselect#49]
This issue isn't fixed yet, but there are two tickets already closed: #38, #32
The error which is produced: https://github.com/bonprix/vaadin-combobox-multiselect/issues/38#issuecomment-323734132

This should do the trick:

```
<build>
	<plugins>
		<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-jar-plugin</artifactId>
		<configuration>
			<excludes>
				<exclude>**/rebel.xml</exclude>
			</excludes>
		</configuration>
	</plugin>
</build>
```

**Comment by thorbenvh8** [comment]
please use version 2.1 :)
