### ISSUE TITLE
clearAll does not update client side VCheckBoxes

### ISSUE THREAD

**Issue by evanzel** [bonprix/vaadin-combobox-multiselect#51]
Congrats on updating this add-on without compatibility classes. I have been waiting for this, since this add-on was the one single reason I still was using compatibility jars.
Allow me to report a couple of issues:

The clear command, while it does update the selection server side, 
it still leaves the checkboxes checked.

**Comment by thorbenvh8** [comment]
thanks for this bug, the way i tested it, i couldnt see it :)
check version 2.1 :)
