### ISSUE TITLE
checkboxes don't work clicking on the icon

### ISSUE THREAD

**Issue by evanzel** [bonprix/vaadin-combobox-multiselect#52]
And the second issue I am reporting is that clicking on the checkboxes does not seem to work.
I have to click on the caption.

**Comment by mathisdt** [comment]
There was a CSS fix for the Vaadin 7 version of the multiselect-combobox so the icon became clickable, but it doesn't work anymore:

`.v-checkbox > input ~ label:before, .v-checkbox > input ~ label:after {`
`content: "";`
`display: inline-block;`
`box-sizing: border-box;`
`width: 20px;`
`height: 20px;`
`position: absolute;`
`left: 8px;`
`border-radius: 4px;`
`font-size: 13px;`
`text-align: center;`
`}`

**Comment by thorbenvh8** [comment]
couldnt use your css rules, but thank you :)
no workaround anymore :)

**Comment by thorbenvh8** [comment]
version 2.1
