### ISSUE TITLE
erratic behaviour selecting/desececting item at a page other than 0

### ISSUE THREAD

**Issue by evanzel** [bonprix/vaadin-combobox-multiselect#53]
This one is tricky. I spotted it in my project and confirmed it in the included demo.
Steps to reproduce:
In the first 'Normal' ComboBoxMultiselect move to page 51-60 or a higher range and select an item.
Suggestions will clear for some reason.
It does not happen in previous pages.

.

**Comment by thorbenvh8** [comment]
i looked at the problem it is some strange behaviour...
We will give it to Vaadin for a check, I cant find the problem.

**Comment by thorbenvh8** [comment]
vaadin responded and fixed it :)
done in 2.2 :)
