### ISSUE TITLE
Example code has errors

### ISSUE THREAD

**Issue by Spielzeug** [bonprix/vaadin-combobox-multiselect#58]
Hello,

example code on vaadin directory addon page has 2 errors: setInptuPrompt and addItems are undefined for ComboBoxMultiselect. There is setPlaceholder and setItems methods instead.

**Comment by sebastianfilke** [comment]
There is another funny thing. The example code does not use generics. But Vaadin 8 is made for that!

`final ComboBoxMultiselect comboBoxMultiselect = new ComboBoxMultiselect();`

**Comment by thorbenvh8** [comment]
updated readme and vaadin plugin page :)
