### ISSUE TITLE
Select All option

### ISSUE THREAD

**Issue by marpaj** [bonprix/vaadin-combobox-multiselect#6]
HI,
It is a nice component, good work! 
Do you think to add a "select all" option like clear option?

**Comment by thorbenvh8** [comment]
Hi,
we have added it in the last release 1.1.5 :)
Thorben :)

**Comment by marpaj** [comment]
Hi, 
thank you for your answer! I had not installed the last version.
i tried with the 1.1.5 version and I found the method setShowSelectAllButton. I had implemented the ShowButton and passed it. 
However, it doesn't work. Any selection is not executed. I don't know why, because it worked before change the version. Maybe I have to do something more?

Thanks again
Marcos

**Comment by thorbenvh8** [comment]
I cant really refer to your example, could you give some code to read? :)

**Comment by marpaj** [comment]
Sorry for my late response. I hope to explain it better this time :)
I have two comboBox multiselect. When I select an item (or option) in the first one, a valueChangeListener updates the items of the second one and select all these new items. 
It worked with the old version. However, with the 1.1.5 version, the same code does not work. It execute well the method selectAll() in the valueChangeListener but it does not show any option selected. The setImmediate() is to true. 
Do you think It depends of the paintContent()?
Thank in advance

**Comment by thorbenvh8** [comment]
sorry could you give some code example?

**Comment by thorbenvh8** [comment]
do to inactivity closed
