### ISSUE TITLE
rebel.xml part of artifact

### ISSUE THREAD

**Issue by chkpnt** [bonprix/vaadin-combobox-multiselect#8]
JRebel is showing me the warning `Invalid 'dir' defined in class path of rebel.xml`.

The reason is the presence of `rebel.xml` in `vaadin-combobox-multiselect-1.1.7.jar`. I guess this file, which refers to a directory under `/Users/thorbenvh8/Documents/`, was added unintentionally.

**Comment by thorbenvh8** [comment]
yes def :)
will be fixed with your pull request? ;)

**Comment by thorbenvh8** [comment]
fixed in 1.1.8, thanks @stoerti
