### ISSUE TITLE
Configurable clearMenuItem / selectAllMenuItem for localization

### ISSUE THREAD

**Issue by chkpnt** [bonprix/vaadin-combobox-multiselect#9]
Currently the text shown for the `clearMenuItem` as well as for the `selectAllMenuItem` is hard-coded in the [client-side-part](https://github.com/bonprix/vaadin-combobox-multiselect/blob/07e24c39ece6a9ae699b950dc2a119df82bacfd7/vaadin-combobox-multiselect/src/main/java/org/vaadin/addons/comboboxmultiselect/client/VComboBoxMultiselect.java#L841).

Localization would be possible, if the string was configurable from the server side.

**Comment by thorbenvh8** [comment]
Oh yeah, sorry.
I would be open for a pull request, option for you? :)

**Comment by chkpnt** [comment]
Indeed, it is. Just give me some days.

**Comment by fabioebner** [comment]
how I configure to show messages in Pt_Br ? instead selectAll I need, "Selecionar Todos" and instead "clear" I need "Limpar"  

tks

**Comment by thorbenvh8** [comment]
I will work on it this week to set individual text for the buttons. :)

**Comment by chkpnt** [comment]
This reminds me of my previous commitment, which totally get out of my head. Sorry!

But reading your last comment and knowing my calendar, I have to withdraw.

**Comment by thorbenvh8** [comment]
fixed in 1.1.8 :)
